// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6KORqmXxWLDJqBriSwhzXjptnXxwtlPY',
    appId: '1:307065531115:web:c42f3fd148ab7750f32cae',
    messagingSenderId: '307065531115',
    projectId: 'food-delivery-eff48',
    authDomain: 'food-delivery-eff48.firebaseapp.com',
    storageBucket: 'food-delivery-eff48.firebasestorage.app',
    measurementId: 'G-K9P9ZD0J9Z',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_UfVtQyCH8Zdq6b13t_BLPehNQ6kjvUA',
    appId: '1:307065531115:ios:100bc98bb5cc2946f32cae',
    messagingSenderId: '307065531115',
    projectId: 'food-delivery-eff48',
    storageBucket: 'food-delivery-eff48.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_UfVtQyCH8Zdq6b13t_BLPehNQ6kjvUA',
    appId: '1:307065531115:ios:100bc98bb5cc2946f32cae',
    messagingSenderId: '307065531115',
    projectId: 'food-delivery-eff48',
    storageBucket: 'food-delivery-eff48.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6KORqmXxWLDJqBriSwhzXjptnXxwtlPY',
    appId: '1:307065531115:web:49fb10ad09303d5bf32cae',
    messagingSenderId: '307065531115',
    projectId: 'food-delivery-eff48',
    authDomain: 'food-delivery-eff48.firebaseapp.com',
    storageBucket: 'food-delivery-eff48.firebasestorage.app',
    measurementId: 'G-DEJPEY3LNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2fRPQ23gKq6Dbaa3_V12ibTLhVI2yJFA',
    appId: '1:307065531115:android:d97e9400879a3327f32cae',
    messagingSenderId: '307065531115',
    projectId: 'food-delivery-eff48',
    storageBucket: 'food-delivery-eff48.firebasestorage.app',
  );

}