name: food_delivery
description: Food Delivery App with MVVM, Riverpod, built_value, SQLite

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Immutable Models
  built_value: ^8.9.2
  built_collection: ^5.1.1

  # Local Database
  sqflite: ^2.3.2
  path: ^1.9.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  go_router: ^17.1.0
  cloud_firestore: ^6.1.3
  intl: ^0.20.2
  async: ^2.13.0
  patrol_cli: ^4.2.0
  sqflite_common_ffi_web: ^1.1.1
  appwrite: ^23.1.0
  image_picker: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.5.4
  built_value_generator: ^8.9.2
  riverpod_generator: ^2.6.1
  flutter_lints: ^3.0.0
  patrol: ^4.3.0
  dart_appwrite: ^22.0.0

patrol:
  app_name: food_delivery
  android:
    package: com.example.foodDelivery
flutter:
  uses-material-design: true