name: Flutter APK Build
#on tells when to run the scrpt when push happens  in the main it  runs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # temporary Windows machine

    steps:
      #checkout repository code
      - uses: actions/checkout@v4

      # set up Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # install dependencies
      - run: flutter pub get
        working-directory: Flutter/Food_Deliver/food_delivery

      #build release APK (in nested Flutter app)
      - run: flutter build apk --release
        working-directory: Flutter/Food_Deliver/food_delivery

      # upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: Flutter/Food_Deliver/food_delivery/build/app/outputs/flutter-apk/app-release.apk